name: 'course_advanced_dbt'
version: '1.0.0'
config-version: 2

profile: 'course_advanced_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: 'logs'
target-path: 'target'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_packages"

# set your model fanout threshold to 10 instead of 3
vars:
  dbt_project_evaluator:
    models_fanout_threshold: 10

seeds:
  course_advanced_dbt:
    unit_testing:
      +schema: unit_testing
      +tags: unit_testing
      unit_test_expected_output_mrr:
        +column_types:
          surrogate_key: VARCHAR(32)
          date_month: DATE
          user_id: NUMBER(38,0)
          subscription_id: NUMBER(38,0)
          starts_at: TIMESTAMP_NTZ(9)
          ends_at: TIMESTAMP_NTZ(9)
          plan_name: VARCHAR(16777216)
          mrr_amount: NUMBER(18,2)
          mrr_change: NUMBER(19,2)
          retained_mrr_amount: NUMBER(18,2)
          previous_month_mrr_amount: NUMBER(18,2)
          change_category: VARCHAR(12)
          month_retained_number: NUMBER(9,0)

      unit_test_input_int_dates:
        +column_types:
          calendar_date: DATE
          date_week: DATE
          date_month: DATE
          date_quarter: DATE
          date_year: DATE
          day_of_month: NUMBER(2,0)
          year_num: NUMBER(4,0)
          quarter_num: NUMBER(2,0)
          month_num: NUMBER(2,0)

      unit_test_input_dim_subscriptions:
        +column_types:
          subscription_id: NUMBER(38,0)
          subscription_plan_id: NUMBER(38,0)
          user_id: NUMBER(38,0)
          starts_at: TIMESTAMP_NTZ(9)
          ends_at: TIMESTAMP_NTZ(9)
          plan_name: VARCHAR(16777216)
          pricing: NUMBER(18,2)
          billing_period: VARCHAR(16777216)

models:
  course_advanced_dbt:
    +materialized: view
    +grants:
      select: ['transformer', 'reporter']

    staging:
      +schema: staging

    intermediate:
      +schema: intermediate

    marts:
      core:
        +schema: core_reporting
      finance:
        +schema: finance
      product:
        +schema: product

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
